version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: postgres14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./postgres_init/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
  urlshortener:
    depends_on:
      - db
    image: golang:1.16-alpine
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: shortener
    ports:
      - "8080:8080"
volumes:
  database-data: